name: pocketra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1

  # State management
  flutter_riverpod: ^2.5.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App icon and splash screen generators
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  # Assets folder
  assets:
    - assets/icon/
    - assets/images/