// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcp-7kYhuedlPh_ehiKaQ4TyAdLbGtMA',
    appId: '1:195018849237:web:b7fba6cf141bb690c15b5c',
    messagingSenderId: '195018849237',
    projectId: 'pocketra-21bc8',
    authDomain: 'pocketra-21bc8.firebaseapp.com',
    storageBucket: 'pocketra-21bc8.firebasestorage.app',
    measurementId: 'G-0H20G5Z2CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwd6BZm2rptjoGZWPICg9Dq5m-rOPJaBU',
    appId: '1:195018849237:android:d00870b90d82f4ecc15b5c',
    messagingSenderId: '195018849237',
    projectId: 'pocketra-21bc8',
    storageBucket: 'pocketra-21bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfW72mOuLSHIyN_ZNYebEjju2bfNaR06s',
    appId: '1:195018849237:ios:c304f14f1162b960c15b5c',
    messagingSenderId: '195018849237',
    projectId: 'pocketra-21bc8',
    storageBucket: 'pocketra-21bc8.firebasestorage.app',
    iosBundleId: 'com.example.pocketra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfW72mOuLSHIyN_ZNYebEjju2bfNaR06s',
    appId: '1:195018849237:ios:c304f14f1162b960c15b5c',
    messagingSenderId: '195018849237',
    projectId: 'pocketra-21bc8',
    storageBucket: 'pocketra-21bc8.firebasestorage.app',
    iosBundleId: 'com.example.pocketra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcp-7kYhuedlPh_ehiKaQ4TyAdLbGtMA',
    appId: '1:195018849237:web:4904b80e4706b278c15b5c',
    messagingSenderId: '195018849237',
    projectId: 'pocketra-21bc8',
    authDomain: 'pocketra-21bc8.firebaseapp.com',
    storageBucket: 'pocketra-21bc8.firebasestorage.app',
    measurementId: 'G-7TSLS8MTMN',
  );
}
