// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGPwtxQy9LFpPqxxCqD-OPXXVhZVxyVE',
    appId: '1:1051101578500:web:bc493bd2b556ea04133c51',
    messagingSenderId: '1051101578500',
    projectId: 'pocketra-4f814',
    authDomain: 'pocketra-4f814.firebaseapp.com',
    storageBucket: 'pocketra-4f814.firebasestorage.app',
    measurementId: 'G-8KGFNSZVTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_JoWcQC6Si2OWphoXJ_FINOQz84SMRoA',
    appId: '1:1051101578500:android:347aa78db3501663133c51',
    messagingSenderId: '1051101578500',
    projectId: 'pocketra-4f814',
    storageBucket: 'pocketra-4f814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eMRsck2mCow_zvtTSD2cIbni3EIjZe4',
    appId: '1:1051101578500:ios:3efe970a2a3a841d133c51',
    messagingSenderId: '1051101578500',
    projectId: 'pocketra-4f814',
    storageBucket: 'pocketra-4f814.firebasestorage.app',
    iosBundleId: 'com.example.pocketra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eMRsck2mCow_zvtTSD2cIbni3EIjZe4',
    appId: '1:1051101578500:ios:3efe970a2a3a841d133c51',
    messagingSenderId: '1051101578500',
    projectId: 'pocketra-4f814',
    storageBucket: 'pocketra-4f814.firebasestorage.app',
    iosBundleId: 'com.example.pocketra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGPwtxQy9LFpPqxxCqD-OPXXVhZVxyVE',
    appId: '1:1051101578500:web:cb449a05e11ec661133c51',
    messagingSenderId: '1051101578500',
    projectId: 'pocketra-4f814',
    authDomain: 'pocketra-4f814.firebaseapp.com',
    storageBucket: 'pocketra-4f814.firebasestorage.app',
    measurementId: 'G-GC5EZCCP2K',
  );
}
